Add pre-hotfix hook to ensure branch name is in the correct pattern

diff --git a/git-flow b/git-flow
--- a/git-flow
+++ b/git-flow
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 BUILD_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-VERSION=2
+VERSION=3
 
 function load_common() {
   gitflow_path="$(which -a git-flow | grep -v "^$BUILD_DIR/git-flow\$" | head -n1)"
@@ -44,16 +44,60 @@ function is_gitflow_extension_current() {
   fi
 }
 
+function write_pre_flow_hotfix_start_hook() {
+  cat << EOF > $HOME/.git-hooks/pre-flow-hotfix-start
+#!/usr/bin/env bash
+
+function load_common() {
+  gitflow_path="\$(which -a git-flow | grep -v "^$BUILD_DIR/git-flow\$" | head -n1)"
+  while [ -h "\$gitflow_path" ]; do
+    # shellcheck disable=SC2155
+    local link=\$(readlink "\$gitflow_path")
+    if expr "\$link" : '/.*' > /dev/null; then
+      gitflow_path="\$link"
+    else
+      gitflow_path="\$(dirname "\$gitflow_path")/\$link"
+    fi
+  done
+  # shellcheck disable=SC2155
+  gitflow_common_file=\$(dirname "\$gitflow_path")/../libexec/bin/gitflow-common
+  . "\$gitflow_common_file"
+  if [[ "\$?" -ne 0 ]]; then
+    echo -e "Failed to source '\$gitflow_common_file': \$?" 1>&2
+    exit 1
+  fi
+}
+
+function run() {
+  local version="\$1"
+  local origin="\$2"
+  local branch="\$3"
+  local base="\$4"
+  local pattern='^hotfix/(([[:alpha:]]+-[[:digit:]]+)|([[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}))(\.[[:digit:]]+)?\$'
+
+  load_common
+
+  if [[ ! \$branch =~ \$pattern ]]; then
+    die "invalid hotfix branch name '\$branch', must be similar to hotfix/TOP-1234, hotfix/MU-1234.1, hotfix/2019-07-11, or hotfix/2019-07-11.1"
+  fi
+}
+
+run "\$@"
+
+EOF
+  chmod +x $HOME/.git-hooks/pre-flow-hotfix-start
+}
+
 function write_pre_flow_hotfix_finish_hook() {
   cat << EOF > $HOME/.git-hooks/pre-flow-hotfix-finish
 #!/usr/bin/env bash
 
 function run() {
-local name="\$1"
-local origin="\$2"
-local branch="\$3"
+  local name="\$1"
+  local origin="\$2"
+  local branch="\$3"
 
-$HOME/.git-hooks/pre-flow-finish "hotfix" "\$MASTER_BRANCH" "\$name" "\$origin" "\$branch"
+  $HOME/.git-hooks/pre-flow-finish "hotfix" "\$MASTER_BRANCH" "\$name" "\$origin" "\$branch"
 }
 
 run "\$@"
@@ -67,11 +111,11 @@ function write_post_flow_hotfix_finish_hook() {
 #!/usr/bin/env bash
 
 function run() {
-local name="\$1"
-local origin="\$2"
-local branch="\$3"
+  local name="\$1"
+  local origin="\$2"
+  local branch="\$3"
 
-$HOME/.git-hooks/post-flow-finish "hotfix" "\$MASTER_BRANCH" "\$name" "\$origin" "\$branch"
+  $HOME/.git-hooks/post-flow-finish "hotfix" "\$MASTER_BRANCH" "\$name" "\$origin" "\$branch"
 }
 
 run "\$@"
@@ -85,11 +129,11 @@ function write_pre_flow_feature_finish_hook() {
 #!/usr/bin/env bash
 
 function run() {
-local name="\$1"
-local origin="\$2"
-local branch="\$3"
+  local name="\$1"
+  local origin="\$2"
+  local branch="\$3"
 
-$HOME/.git-hooks/pre-flow-finish "feature" "\$DEVELOP_BRANCH" "\$name" "\$origin" "\$branch"
+  $HOME/.git-hooks/pre-flow-finish "feature" "\$DEVELOP_BRANCH" "\$name" "\$origin" "\$branch"
 }
 
 run "\$@"
@@ -103,11 +147,11 @@ function write_post_flow_feature_finish_hook() {
 #!/usr/bin/env bash
 
 function run() {
-local name="\$1"
-local origin="\$2"
-local branch="\$3"
+  local name="\$1"
+  local origin="\$2"
+  local branch="\$3"
 
-$HOME/.git-hooks/post-flow-finish "feature" "\$DEVELOP_BRANCH" "\$name" "\$origin" "\$branch"
+  $HOME/.git-hooks/post-flow-finish "feature" "\$DEVELOP_BRANCH" "\$name" "\$origin" "\$branch"
 }
 
 run "\$@"
@@ -294,6 +338,7 @@ function write_hooks() {
   mkdir -p $HOME/.git-hooks
   write_pre_flow_finish_hook
   write_post_flow_finish_hook
+  write_pre_flow_hotfix_start_hook
   write_pre_flow_hotfix_finish_hook
   write_post_flow_hotfix_finish_hook
   write_pre_flow_feature_finish_hook
