Allow squash message commit template to be modified and the commit message to be modified

diff --git a/git-flow b/git-flow
--- a/git-flow
+++ b/git-flow
@@ -60,19 +60,26 @@ function run() {
   local git_commit_author_email
   git_commit_author_email="\$(git config --get user.email)" || die "failed to find git config: user.email"
   local git_commit_author="\$git_commit_author_name <\$git_commit_author_email>"
+  local git_squash_commit_format
+  git_squash_commit_format="\$(git config --get gitflow.feature.finish.squash.format)"
+  if [[ "\$?" != "0" ]]; then
+    git_squash_commit_format="%h%x09%s%x09%aN <%aE>%x09%ad"
+  fi
   local git_commit_details
-  git_commit_details="\$(git log "\$base_branch..\$branch" --oneline | sed 's/^/    /')" || die "failed to get commit details"
+  git_commit_details="\$(git log "\$base_branch..\$branch" --pretty="format:\$git_squash_commit_format" | sed 's/^/    /')" || die "failed to get commit details"
   local git_merge_base
   git_merge_base="\$(git merge-base HEAD \$base_branch)" || die "failed to find merge base"
-  git reset --soft \$git_merge_base || die "failed to reset back to merge base"
-  {
-    cat <<EOM
+  git_do reset --soft \$git_merge_base || die "failed to reset back to merge base"
+  local git_commit_message_file
+  git_commit_message_file="\$(mktemp)" || die "failed to create temp file for git commit message"
+  cat <<EOM > \$git_commit_message_file
 Squashed commit of the following:
 
 \${git_commit_details}
 EOM
-} | git commit --author="\$git_commit_author" --file - || die "failed to squash commits"
-  git rebase \$base_branch || die "failed to rebase onto base branch"
+  trap "rm -rf \$git_commit_message_file" EXIT
+  git_do commit --author="\$git_commit_author" --edit --file - || die "failed to squash commits"
+  git_do rebase \$base_branch || die "failed to rebase onto base branch"
   exit 0
 }
 
